#!/bin/bash

# Time:   Gaussian
# Energy: Gaussian
# transverse: parabolic

sddssequence -pipe=out -define=z,type=double -seq=begin=-1,end=1,n=100 \
  | sddsprocess -pipe=in pDist.sdds \
  "-define=col,P,1 z sqr - 3 * 4 /"

sddssampledist -pipe=out -samples=100000 \
  -gaussian=column=t,sigma=1e-12 \
  -gaussian=column=p,mean=1000,sigma=2 \
  -column=indep=z,df=P,output=x,units=m,dataFile=pDist.sdds,factor=1e-3 \
  -column=indep=z,df=P,output=xp,units=,dataFile=pDist.sdds,factor=1e-3 \
  -column=indep=z,df=P,output=y,units=m,dataFile=pDist.sdds,factor=1e-3 \
  -column=indep=z,df=P,output=yp,units=,dataFile=pDist.sdds,factor=1e-3 \
  | sddsmatchtwiss -pipe=in dist.sdds \
    -xplane=beta=1,alpha=0 \
    -yplane=beta=2,alpha=-5

sddsplot -layout=2,2 -sep \
  -column=t,p dist.sdds -graph=dot \
  -column=x,y dist.sdds -graph=dot \
  -column=xp,yp dist.sdds -graph=dot \
  -column=x,xp dist.sdds -graph=dot \
  -column=y,yp dist.sdds -graph=dot 

sddsmultihist dist.sdds hist.sdds \
    -bins=100 \
    -separate \
    -column=x,xp,y,yp,t,p 

sddsplot -column=*,%sFrequency hist.sdds -sep 
