#!/bin/bash

sddscollapse Basic.twi -pipe=out \
    | sddsconvert -pipe  -retain=col,Jx,Jy,Jdelta,ex0,U0,Sdelta0,pCentral \
    | sddsprocess -pipe "-define=col,dDelta,U0 pCentral mev * / chs" \
    | sddstranspose -pipe -oldColumnNames=ColumnName \
    | sddsconvert -pipe -rename=col,Column=ParameterValue \
    | sddsxref SREffects.xref -nowarning -pipe -match=ColumnName -take=* \
    | tee SREffects.sdds \
    | sddsprintout -pipe -col

