#!/bin/sh  
# \
exec oagtclsh "$0" "$@"

set auto_path [linsert $auto_path 0  /usr/local/oag/apps/lib/$env(HOST_ARCH)]
set auto_path [linsert $auto_path 0 /usr/local/oag/lib_patch/$env(HOST_ARCH)]
APSStandardSetup

set p1 [exec sddsprocess ../L1O_L3FS5/longit.cen -pipe=out -clip=0,1,invert | sdds2stream -pipe -col=pCentral]

file delete -force transverse.ele.log
catch {exec elegant transverse.ele -macro=p1=$p1 >& transverse.ele.log } result

