#!/bin/sh  
# \
exec oagtclsh "$0" "$@"

set auto_path [linsert $auto_path 0  /usr/local/oag/apps/lib/$env(HOST_ARCH)]
set auto_path [linsert $auto_path 0 /usr/local/oag/lib_patch/$env(HOST_ARCH)]
APSStandardSetup

set nux0 2.169
set nuy0 1.217
set nux1 2.217
set nuy1 1.169
set nSteps 30
set dnux [expr ($nux1-$nux0)/($nSteps-1.0)]
set dnuy [expr ($nuy1-$nuy0)/($nSteps-1.0)]

set index 0
set start null.sdds
while {$index<$nSteps} {
      set nux [expr $nux0+$dnux*$index]
      set nuy [expr $nuy0+$dnuy*$index]
      set rootname scan-[format %02d $index]
      catch {exec elegant changeTuneTemplate.ele -macro=startingPoint=$start,rootname=$rootname,nuxTarget=$nux,nuyTarget=$nuy} result
      puts stderr "$result"
      incr index
      set start $rootname.param
}
