#!/bin/sh  
# \
exec oagtclsh "$0" "$@"

set auto_path [linsert $auto_path 0  /usr/local/oag/apps/lib/$env(HOST_ARCH)]
set auto_path [linsert $auto_path 0 /usr/local/oag/lib_patch/$env(HOST_ARCH)]
APSStandardSetup

set usage "usage: matchChicane -dZB4 <m> -R56 <value> -rootname <string> "
set dZB4 0.05
set R56 -0.038
set rootname ""
set lattice chicaneOpt.lte
set args $argv
if {[APSStrictParseArguments {dZB4 R56 rootname lattice}] || \
        ![string length $rootname] || ![string length $lattice] || \
        ![file exists $lattice]} {
    puts stderr $usage
    exit 1
}
if [file exists $rootname.ele] {
    puts stderr "Already used: $rootname"
    exit 1
}
set ZTotal [expr 3.19137-0.008990474709022]
set LB 0.192
set L1 [expr 0.65-($LB-0.12)]
set L2 [expr 0.5-($LB-0.12)+0.07]
exec replace chicaneOptTemplate.ele $rootname.ele \
  -orig=<L1>,<L2>,<dZB4>,<R56>,<rootname>,<lattice>,<LB>,<ZTotal> \
  -repl=$L1,$L2,$dZB4,$R56,$rootname,$lattice,$LB,$ZTotal
catch {exec elegant $rootname.ele}  result
puts stdout "$result"
exit 
