#!/bin/sh  
# \
exec oagtclsh "$0" "$@"

set auto_path [linsert $auto_path 0  /usr/local/oag/apps/lib/$env(HOST_ARCH)]
set auto_path [linsert $auto_path 0 /usr/local/oag/lib_patch/$env(HOST_ARCH)]
APSStandardSetup

eval exec sddscombine [lsort [glob scan-*.twi]] -collapse scan.twic -overwrite
eval exec sddscombine [lsort [glob scan-*.param]] -pipe=out \
     | sddsprocess -pipe \
     -filter=col,ElementOccurence,1,1 \
     -match=col,ElementParameter=K? \
     -match=col,ElementType=K* \
     -print=col,ElementTag,%s.%s,ElementName,ElementParameter \
     | sddsconvert -pipe -retain=col,ElementTag,ParameterValue \
     | sddstranspose -pipe \
     | sddscombine -pipe -merge \
     | sddsprocess -pipe "{-define=col,t,0.022 n_rows 1 - / i_row * 1e-8 -,units=s}" \
     | sddsxref -pipe=in scan.twic -take=* rampProgram.sdds





