#!/bin/bash

\rm daTrack.esl
elasticScatteringLifetime -aperture daTrack.aper -name Clipped -twiss daTrack.twi -output daTrack.esl -sPeriodic 30.667 -pressure 1 -customGas H2:0.65,H2O:0.02,CH4:0.07,CO:0.22,CO2:0.04
sddsprintout -parameter=*Ave daTrack.esl

\rm lmaTrack.bsl
bremsstrahlungLifetime -aperture lmaTrack.mmap  -name "" -output lmaTrack.bsl -pressure 1 -customGas H2:0.65,H2O:0.02,CH4:0.07,CO:0.22,CO2:0.04
sddsprintout -parameter=*Ave lmaTrack.bsl
